name: matthieuthuetdev-apache
services:
  apache: 
    image: httpd 
    container_name: matthieuthuetdev-httpd
    restart: always 
    volumes: 
      - './:/usr/local/apache2/htdocs'
    ports: 
      - '3000:80'